import "@/styles/globals.css";
import Head from "next/head";
import { ApolloClient, InMemoryCache, ApolloProvider } from "@apollo/client";
import { InjectedConnector } from "wagmi/connectors/injected";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import React from "react";
import { URL_QUERY_GRAPHQL } from "@/utils/constants";
import { configureChains, createClient, WagmiConfig } from "wagmi";
import { mainnet, polygon, polygonMumbai } from "wagmi/chains";
import { alchemyProvider } from "wagmi/providers/alchemy";
import { publicProvider } from "wagmi/providers/public";

const { chains, provider, webSocketProvider } = configureChains(
  [mainnet, polygonMumbai, polygon],
  [alchemyProvider({ apiKey: "yourAlchemyApiKey" }), publicProvider()]
);

const wagmiClient = createClient({
  autoConnect: true,
  connectors: [new InjectedConnector({ chains })],
  provider,
});

const client = new ApolloClient({
  uri: URL_QUERY_GRAPHQL,
  cache: new InMemoryCache(),
});

export default function App({ Component, pageProps }) {
  const [ready, setReady] = React.useState(false);
  React.useEffect(() => {
    setReady(true);
  }, []);

  return (
    <>
      <Head>
        <title>Roller Dao</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!ready ? (
        <div className="h-screen w-screen flex justify-center items-center">
          Loading..
        </div>
      ) : (
        <ApolloProvider client={client}>
          <WagmiConfig client={wagmiClient}>
            <Header />
            <Component {...pageProps} />
            <Footer />
          </WagmiConfig>
        </ApolloProvider>
      )}
    </>
  );
}
